name: Go

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  verify:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - name: df
      run: |
        while true; do date >> df.log && sleep 10; done &
        sleep 11
        pkill -P $$
    - name: test
      run: |
        df -h
        sudo du -sh /* | sort -h
        sudo du -sh /var/* | sort -h
        sudo du -sh /opt/* | sort -h
        sudo du -sh /mnt/* | sort -h
        sudo du -sh /usr/* | sort -h
        sudo du -sh /usr/local/* | sort -h
        sudo du -sh /usr/local/lib/* | sort -h
        
        ls -la /mnt
        
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        
        df -h
        sudo du -sh /* | sort -h
        
        false
