name: Go

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  verify:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - name: test
      run: echo release-1.0

